// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreEntityFrameworkCodeFirstApproach.Models;

#nullable disable

namespace coreEntityFrameworkCodeFirstApproach.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240101211227_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("coreEntityFrameworkCodeFirstApproach.Models.Customer", b =>
                {
                    b.Property<int>("CustorerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustorerId"));

                    b.Property<double>("CustomerAmount")
                        .HasColumnType("float");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustorerId");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
